POST http://aaccb8ee0a57f4451bacea0f123731c4-432690050.eu-central-1.elb.amazonaws.com/tasks
Content-Type: application/json

{
  "name": "Write documentation 2",
  "description": "Prepare API docs for the new feature",
  "completed": false,
  "projectId": "ff7bf134-1483-49c8-9af8-d4dc60c80983"
}
