PUT
    http://aaccb8ee0a57f4451bacea0f123731c4-432690050.eu-central-1.elb.amazonaws.com/tasks/2817fd7d-1613-46e9-b58f-be792a5a7c19
Content-Type: application/json

{
  "name": "Write updated docs",
  "description": "Documentation updated 2",
  "completed": true,
  "projectId": 42
}
